// <auto-generated />
namespace School.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KhoitaocacbangcuaIndentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoitaocacbangcuaIndentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202303161521338_Khoi tao cac bang cua Indentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
